"""add ai_engine tables (artifacts, trace, trace_event)

Revision ID: 185f6c3280b9
Revises: c7_fix_cascade
Create Date: 2026-05-12 16:59:16.637229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185f6c3280b9'
down_revision: Union[str, Sequence[str], None] = 'c7_fix_cascade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_trace',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('model_slot', sa.String(length=50), nullable=False),
    sa.Column('budget_initial_json', sa.Text(), nullable=False),
    sa.Column('budget_final_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_trace_run_id'), 'ai_agent_trace', ['run_id'], unique=True)
    op.create_index(op.f('ix_ai_agent_trace_school_id'), 'ai_agent_trace', ['school_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_trace_session_id'), 'ai_agent_trace', ['session_id'], unique=False)
    op.create_table('ai_artifacts',
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_tool', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('pii_level', sa.String(length=20), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('preview_json', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_artifacts_artifact_id'), 'ai_artifacts', ['artifact_id'], unique=True)
    op.create_index(op.f('ix_ai_artifacts_run_id'), 'ai_artifacts', ['run_id'], unique=False)
    op.create_index(op.f('ix_ai_artifacts_school_id'), 'ai_artifacts', ['school_id'], unique=False)
    op.create_table('ai_agent_trace_event',
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('args_ref', sa.String(length=64), nullable=True),
    sa.Column('result_ref', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('pii_level', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['ai_agent_trace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_trace_event_trace_id'), 'ai_agent_trace_event', ['trace_id'], unique=False)
    op.create_index('ix_trace_event_trace_seq', 'ai_agent_trace_event', ['trace_id', 'seq'], unique=False)


def downgrade() -> None:
    """Drop ai_engine tables."""
    op.drop_index('ix_trace_event_trace_seq', table_name='ai_agent_trace_event')
    op.drop_index(op.f('ix_ai_agent_trace_event_trace_id'), table_name='ai_agent_trace_event')
    op.drop_table('ai_agent_trace_event')
    op.drop_index(op.f('ix_ai_artifacts_school_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_run_id'), table_name='ai_artifacts')
    op.drop_index(op.f('ix_ai_artifacts_artifact_id'), table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_index(op.f('ix_ai_agent_trace_session_id'), table_name='ai_agent_trace')
    op.drop_index(op.f('ix_ai_agent_trace_school_id'), table_name='ai_agent_trace')
    op.drop_index(op.f('ix_ai_agent_trace_run_id'), table_name='ai_agent_trace')
    op.drop_table('ai_agent_trace')
    # ### end Alembic commands ###
