"""add adaptive learning tables

Revision ID: 30da2c2e9aa6
Revises: ebe274b55ca4
Create Date: 2026-04-06 17:57:34.994674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30da2c2e9aa6'
down_revision: Union[str, Sequence[str], None] = 'ebe274b55ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptive_cards',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('da_id', sa.String(length=100), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'da_id')
    )
    op.create_table('answer_logs',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('exam_id', sa.String(length=36), nullable=True),
    sa.Column('da_ids', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('score_rate', sa.Float(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'exam_id', 'student_id', 'question_id')
    )
    op.create_index(op.f('ix_answer_logs_school_id'), 'answer_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_answer_logs_student_id'), 'answer_logs', ['student_id'], unique=False)
    op.create_table('da_bkt_params',
    sa.Column('da_id', sa.String(length=100), nullable=False),
    sa.Column('p_init', sa.Float(), nullable=False),
    sa.Column('p_transit', sa.Float(), nullable=False),
    sa.Column('p_guess', sa.Float(), nullable=False),
    sa.Column('p_slip', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('da_id')
    )
    op.create_table('da_catalog_snapshot',
    sa.Column('da_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('module', sa.String(length=10), nullable=True),
    sa.Column('concept_ids', sa.JSON(), nullable=True),
    sa.Column('study_unit_ids', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('da_id')
    )
    op.create_table('da_knowledge_point_map',
    sa.Column('da_id', sa.String(length=100), nullable=False),
    sa.Column('knowledge_point_id', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('da_id', 'knowledge_point_id')
    )
    op.create_table('question_da_override',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('da_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('student_da_mastery',
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('da_id', sa.String(length=100), nullable=False),
    sa.Column('mastery_prob', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('last_answer_at', sa.DateTime(), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'da_id')
    )
    op.create_index(op.f('ix_student_da_mastery_da_id'), 'student_da_mastery', ['da_id'], unique=False)
    op.create_index(op.f('ix_student_da_mastery_school_id'), 'student_da_mastery', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_da_mastery_student_id'), 'student_da_mastery', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_da_mastery_student_id'), table_name='student_da_mastery')
    op.drop_index(op.f('ix_student_da_mastery_school_id'), table_name='student_da_mastery')
    op.drop_index(op.f('ix_student_da_mastery_da_id'), table_name='student_da_mastery')
    op.drop_table('student_da_mastery')
    op.drop_table('question_da_override')
    op.drop_table('da_knowledge_point_map')
    op.drop_table('da_catalog_snapshot')
    op.drop_table('da_bkt_params')
    op.drop_index(op.f('ix_answer_logs_student_id'), table_name='answer_logs')
    op.drop_index(op.f('ix_answer_logs_school_id'), table_name='answer_logs')
    op.drop_table('answer_logs')
    op.drop_table('adaptive_cards')
    # ### end Alembic commands ###
