"""add_school_settings_modules

Revision ID: b71cef336bfa
Revises: 8b3f659c1a2a
Create Date: 2026-03-29 19:58:34.072493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71cef336bfa'
down_revision: Union[str, Sequence[str], None] = '8b3f659c1a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_modules',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'module_code', name='uq_school_modules_school_code')
    )
    op.create_index(op.f('ix_school_modules_school_id'), 'school_modules', ['school_id'], unique=False)
    op.create_table('school_settings',
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'key', name='uq_school_settings_school_key')
    )
    op.create_index(op.f('ix_school_settings_school_id'), 'school_settings', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_settings_school_id'), table_name='school_settings')
    op.drop_table('school_settings')
    op.drop_index(op.f('ix_school_modules_school_id'), table_name='school_modules')
    op.drop_table('school_modules')
    # ### end Alembic commands ###
