"""initial: all tables

Revision ID: bdd523549077
Revises: 
Create Date: 2026-03-22 08:06:16.324723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd523549077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('districts', sa.JSON(), nullable=True),
    sa.Column('school_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('registered_schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('api_key_hash', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_version', sa.String(length=50), nullable=True),
    sa.Column('exam_ai_port', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('class_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('grade_number', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joint_exams',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('creator_school_id', sa.String(length=36), nullable=True),
    sa.Column('template_file_path', sa.String(length=500), nullable=True),
    sa.Column('answer_detail_schema', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['creator_school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('student_number', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_number', name='uq_student_school_number')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('grade_ids', sa.JSON(), nullable=True),
    sa.Column('class_ids', sa.JSON(), nullable=True),
    sa.Column('subject_codes', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_results',
    sa.Column('exam_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('detail_scores', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_result_exam_student')
    )
    op.create_table('joint_exam_participants',
    sa.Column('joint_exam_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('score_upload_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['joint_exam_id'], ['joint_exams.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('joint_exam_student_results',
    sa.Column('joint_exam_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_number', sa.String(length=100), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('detail_scores', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['joint_exam_id'], ['joint_exams.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['registered_schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('joint_exam_id', 'school_id', 'subject_code', 'student_number', name='uq_result_student')
    )
    op.create_index('ix_result_ranking', 'joint_exam_student_results', ['joint_exam_id', 'subject_code', 'total_score'], unique=False)
    op.create_index('ix_result_school', 'joint_exam_student_results', ['joint_exam_id', 'school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_result_school', table_name='joint_exam_student_results')
    op.drop_index('ix_result_ranking', table_name='joint_exam_student_results')
    op.drop_table('joint_exam_student_results')
    op.drop_table('joint_exam_participants')
    op.drop_table('exam_results')
    op.drop_table('user_roles')
    op.drop_table('students')
    op.drop_table('joint_exams')
    op.drop_table('exams')
    op.drop_table('class_groups')
    op.drop_table('users')
    op.drop_table('registered_schools')
    op.drop_table('platform_users')
    # ### end Alembic commands ###
