"""add agent_profiles and agent_runs tables, llm_slots tier field

Revision ID: c9587c787c6b
Revises: 2cde4b537c7b
Create Date: 2026-03-30 12:41:27.724271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9587c787c6b'
down_revision: Union[str, Sequence[str], None] = '2cde4b537c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('profile_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('memory_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'school_id', name='uq_profile_user_school')
    )
    op.create_index(op.f('ix_agent_profiles_owner_user_id'), 'agent_profiles', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_agent_profiles_school_id'), 'agent_profiles', ['school_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('tools_resolved', sa.JSON(), nullable=False),
    sa.Column('tools_selected', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('model_tier', sa.String(length=20), nullable=False),
    sa.Column('intent_domains', sa.JSON(), nullable=False),
    sa.Column('token_input', sa.Integer(), nullable=False),
    sa.Column('token_output', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['agent_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_profile_id'), 'agent_runs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.add_column('llm_slots', sa.Column('tier', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_llm_slots_tier'), 'llm_slots', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 用 batch_alter_table 包装以兼容 SQLite（drop_column）
    with op.batch_alter_table('llm_slots') as batch_op:
        batch_op.drop_index(op.f('ix_llm_slots_tier'))
        batch_op.drop_column('tier')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_profile_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_profiles_school_id'), table_name='agent_profiles')
    op.drop_index(op.f('ix_agent_profiles_owner_user_id'), table_name='agent_profiles')
    op.drop_table('agent_profiles')
