"""add agent evolution tables

Revision ID: d5b8da9e0931
Revises: 835926e5c165
Create Date: 2026-04-05 07:34:28.294478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b8da9e0931'
down_revision: Union[str, Sequence[str], None] = '835926e5c165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_findings',
    sa.Column('finding_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notify_roles', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_finding_idempotency')
    )
    op.create_index(op.f('ix_agent_findings_idempotency_key'), 'agent_findings', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_agent_findings_school_id'), 'agent_findings', ['school_id'], unique=False)
    op.create_table('scope_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'user_id', name='uq_scope_school_user')
    )
    op.create_index(op.f('ix_scope_versions_school_id'), 'scope_versions', ['school_id'], unique=False)
    op.create_index(op.f('ix_scope_versions_user_id'), 'scope_versions', ['user_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('trigger_ref', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_workflow_idempotency')
    )
    op.create_index(op.f('ix_workflow_runs_idempotency_key'), 'workflow_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_workflow_runs_school_id'), 'workflow_runs', ['school_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('assignee_role', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['agent_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_school_id'), 'agent_tasks', ['school_id'], unique=False)
    op.create_table('guardian_student_links',
    sa.Column('guardian_user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_user_id', 'student_id', name='uq_guardian_student')
    )
    op.create_index(op.f('ix_guardian_student_links_guardian_user_id'), 'guardian_student_links', ['guardian_user_id'], unique=False)
    op.create_index(op.f('ix_guardian_student_links_school_id'), 'guardian_student_links', ['school_id'], unique=False)
    op.create_index(op.f('ix_guardian_student_links_student_id'), 'guardian_student_links', ['student_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_run_id'), 'workflow_steps', ['run_id'], unique=False)
    op.create_table('class_exam_report',
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('grade_rank', sa.Integer(), nullable=True),
    sa.Column('class_avg', sa.Float(), nullable=True),
    sa.Column('grade_avg', sa.Float(), nullable=True),
    sa.Column('vs_last_exam', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_exam_report_class_id'), 'class_exam_report', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_exam_report_exam_id'), 'class_exam_report', ['exam_id'], unique=False)
    op.create_index(op.f('ix_class_exam_report_school_id'), 'class_exam_report', ['school_id'], unique=False)
    op.create_table('exam_analysis_snapshot',
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_analysis_snapshot_exam_id'), 'exam_analysis_snapshot', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_analysis_snapshot_school_id'), 'exam_analysis_snapshot', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_analysis_snapshot_school_id'), table_name='exam_analysis_snapshot')
    op.drop_index(op.f('ix_exam_analysis_snapshot_exam_id'), table_name='exam_analysis_snapshot')
    op.drop_table('exam_analysis_snapshot')
    op.drop_index(op.f('ix_class_exam_report_school_id'), table_name='class_exam_report')
    op.drop_index(op.f('ix_class_exam_report_exam_id'), table_name='class_exam_report')
    op.drop_index(op.f('ix_class_exam_report_class_id'), table_name='class_exam_report')
    op.drop_table('class_exam_report')
    op.drop_index(op.f('ix_workflow_steps_run_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_guardian_student_links_student_id'), table_name='guardian_student_links')
    op.drop_index(op.f('ix_guardian_student_links_school_id'), table_name='guardian_student_links')
    op.drop_index(op.f('ix_guardian_student_links_guardian_user_id'), table_name='guardian_student_links')
    op.drop_table('guardian_student_links')
    op.drop_index(op.f('ix_agent_tasks_school_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_workflow_runs_school_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_idempotency_key'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_scope_versions_user_id'), table_name='scope_versions')
    op.drop_index(op.f('ix_scope_versions_school_id'), table_name='scope_versions')
    op.drop_table('scope_versions')
    op.drop_index(op.f('ix_agent_findings_school_id'), table_name='agent_findings')
    op.drop_index(op.f('ix_agent_findings_idempotency_key'), table_name='agent_findings')
    op.drop_table('agent_findings')
    # ### end Alembic commands ###
