"""add score_segment_config

Revision ID: ebe274b55ca4
Revises: 1a325e38e941
Create Date: 2026-04-05 18:44:28.315060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe274b55ca4'
down_revision: Union[str, Sequence[str], None] = '1a325e38e941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_segment_config',
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('boundaries', sa.JSON(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_segment_config_school_id'), 'score_segment_config', ['school_id'], unique=False)
    # ### end Alembic commands ###

    # Partial unique indexes — PostgreSQL only (service-layer upsert handles all backends)
    op.execute(sa.text(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_segment_school_default "
        "ON score_segment_config (school_id) WHERE subject_code IS NULL"
    ))
    op.execute(sa.text(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_segment_school_subject "
        "ON score_segment_config (school_id, subject_code) WHERE subject_code IS NOT NULL"
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_segment_config_school_id'), table_name='score_segment_config')
    op.drop_table('score_segment_config')
    # ### end Alembic commands ###
