export const themeOverrides = {
  common: {
    primaryColor: '#1a7a4f',
    primaryColorHover: '#22956a',
    primaryColorPressed: '#145f3d',
    primaryColorSuppl: '#22956a',
    successColor: '#10b981',
    successColorHover: '#059669',
    successColorPressed: '#047857',
    errorColor: '#ef4444',
    warningColor: '#f59e0b',
    infoColor: '#3b82f6',
    fontSize: '16px',
    fontSizeMini: '12px',
    fontSizeTiny: '13px',
    fontSizeSmall: '14px',
    fontSizeMedium: '16px',
    fontSizeLarge: '18px',
    fontSizeHuge: '18px',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    borderColor: '#d4ddd7',
    bodyColor: '#f5f8f6',
    cardColor: '#ffffff',
    tableHeaderColor: '#f0f0ee',
    textColor1: '#0f1a12',
    textColor2: '#3d4f42',
    textColor3: '#6b7d70',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusLarge: '8px',
    borderRadiusSmall: '6px',
    fontWeightStrong: '700',
    fontSizeMedium: '16px',
    fontSizeLarge: '18px',
    fontSizeSmall: '14px',
    heightMedium: '40px',
    heightLarge: '44px',
    heightSmall: '36px',
    paddingMedium: '0 24px',
    paddingLarge: '0 28px',
  },
  Card: {
    borderRadius: '12px',
    borderColor: '#e8efe9',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
    paddingSmall: '18px 22px',
    paddingMedium: '22px 26px',
    titleFontSizeMedium: '18px',
    titleFontSizeSmall: '16px',
    titleFontWeight: '600',
  },
  DataTable: {
    borderRadius: '12px',
    thColor: '#f0f0ee',
    thTextColor: '#72726c',
    thFontWeight: '700',
    tdColor: '#ffffff',
    thPaddingSmall: '14px 20px',
    thPaddingMedium: '16px 24px',
    tdPaddingSmall: '14px 20px',
    tdPaddingMedium: '16px 24px',
    fontSize: '14px',
  },
  Tag: {
    borderRadius: '6px',
    fontSizeSmall: '12px',
    fontSizeMedium: '13px',
    fontSizeTiny: '12px',
    heightSmall: '28px',
    heightMedium: '28px',
    heightTiny: '24px',
  },
  Input: {
    borderRadius: '8px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    heightMedium: '44px',
    heightLarge: '48px',
  },
  Select: {
    borderRadius: '8px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    heightMedium: '44px',
    heightLarge: '48px',
  },
  Dialog: {
    borderRadius: '16px',
    titleFontSize: '20px',
    fontSize: '16px',
  },
  Message: {
    borderRadius: '8px',
    fontSize: '16px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColor: '#3d4f42',
    itemTextColorActive: '#1a7a4f',
    fontSize: '16px',
  },
  Statistic: {
    valueFontSize: '32px',
    labelFontSize: '14px',
  },
  Tabs: {
    tabBorderRadius: '8px',
    tabFontSizeMedium: '16px',
    tabFontSizeLarge: '18px',
    tabFontSizeSmall: '14px',
  },
  Pagination: {
    itemFontSize: '14px',
    buttonFontSize: '14px',
  },
  Form: {
    labelFontSizeTopMedium: '14px',
    feedbackFontSizeMedium: '14px',
  },
  Empty: {
    textColor: '#6b7d70',
    fontSize: '14px',
  },
  Dropdown: {
    fontSize: '16px',
    optionTextColor: '#3d4f42',
  },
}
