export const themeOverrides = {
  common: {
    primaryColor: '#1a2e1f',
    primaryColorHover: '#2d5a3d',
    primaryColorPressed: '#0f1c13',
    primaryColorSuppl: '#2d5a3d',
    successColor: '#2d5a3d',
    successColorHover: '#3a7a52',
    fontSize: '15px',
    fontSizeMini: '13px',
    fontSizeTiny: '13px',
    fontSizeSmall: '14px',
    fontSizeMedium: '15px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    borderRadius: '10px',
    borderColor: '#e2e8e4',
    bodyColor: '#fafcfa',
    cardColor: '#ffffff',
    tableHeaderColor: '#f5faf6',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
  },
  Button: {
    borderRadiusMedium: '50px',
    borderRadiusLarge: '50px',
    borderRadiusSmall: '50px',
  },
  Card: {
    borderRadius: '14px',
    borderColor: '#f0f4f1',
    boxShadow: '0 1px 3px rgba(26,46,31,0.06)',
    paddingSmall: '14px 18px',
    paddingMedium: '18px 22px',
    titleFontSizeMedium: '15px',
    titleFontSizeSmall: '14px',
    titleFontWeight: '600',
  },
  DataTable: {
    borderRadius: '14px',
    thColor: '#f5faf6',
    thPaddingSmall: '10px 16px',
    thPaddingMedium: '12px 16px',
    tdPaddingSmall: '10px 16px',
    tdPaddingMedium: '12px 16px',
    thFontWeight: '600',
    fontSize: '14px',
  },
  Tag: {
    borderRadius: '50px',
  },
  Input: {
    borderRadius: '10px',
  },
  Select: {
    borderRadius: '10px',
  },
  Dialog: {
    borderRadius: '24px',
  },
  Message: {
    borderRadius: '14px',
  },
  Menu: {
    borderRadius: '10px',
  },
  Statistic: {
    valueFontSize: '26px',
    labelFontSize: '13px',
  },
}
