export const themeOverrides = {
  common: {
    primaryColor: '#644CF0',
    primaryColorHover: '#7B68F5',
    primaryColorPressed: '#4F3EC9',
    primaryColorSuppl: '#7B68F5',
    successColor: '#22C55E',
    successColorHover: '#16A34A',
    successColorPressed: '#15803D',
    successColorSuppl: '#4ADE80',
    errorColor: '#dc2626',
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    errorColorSuppl: '#f87171',
    warningColor: '#ED9A51',
    warningColorHover: '#D4842E',
    warningColorPressed: '#B86E1A',
    warningColorSuppl: '#F5B77A',
    infoColor: '#8B7AF5',
    infoColorHover: '#A196F8',
    infoColorPressed: '#6C5CE0',
    infoColorSuppl: '#B4A8F8',
    fontSize: '16px',
    fontSizeMini: '12px',
    fontSizeTiny: '13px',
    fontSizeSmall: '14px',
    fontSizeMedium: '16px',
    fontSizeLarge: '18px',
    fontSizeHuge: '18px',
    borderRadius: '12px',
    borderRadiusSmall: '8px',
    borderColor: '#E8E8EF',
    bodyColor: '#F4F5F9',
    cardColor: '#ffffff',
    tableHeaderColor: '#F4F5F9',
    textColor1: '#09061B',
    textColor2: '#5a5a68',
    textColor3: '#A0A0A8',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'PingFang SC', 'Microsoft YaHei', sans-serif",
  },
  Button: {
    borderRadiusMedium: '12px',
    borderRadiusLarge: '14px',
    borderRadiusSmall: '8px',
    fontWeightStrong: '700',
    fontSizeMedium: '16px',
    fontSizeLarge: '18px',
    fontSizeSmall: '14px',
    heightMedium: '40px',
    heightLarge: '44px',
    heightSmall: '36px',
    paddingMedium: '0 24px',
    paddingLarge: '0 28px',
  },
  Card: {
    borderRadius: '18px',
    borderColor: '#F1F2F6',
    boxShadow: '0 2px 8px rgba(9,6,27,0.04)',
    paddingSmall: '18px 22px',
    paddingMedium: '22px 26px',
    titleFontSizeMedium: '18px',
    titleFontSizeSmall: '16px',
    titleFontWeight: '700',
  },
  DataTable: {
    borderRadius: '14px',
    thColor: '#F4F5F9',
    thTextColor: '#A0A0A8',
    thFontWeight: '700',
    tdColor: '#ffffff',
    thPaddingSmall: '14px 20px',
    thPaddingMedium: '16px 24px',
    tdPaddingSmall: '14px 20px',
    tdPaddingMedium: '16px 24px',
    fontSize: '14px',
  },
  Tag: {
    borderRadius: '999px',
    fontSizeSmall: '12px',
    fontSizeMedium: '13px',
    fontSizeTiny: '12px',
    heightSmall: '28px',
    heightMedium: '28px',
    heightTiny: '24px',
  },
  Input: {
    borderRadius: '12px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    heightMedium: '44px',
    heightLarge: '48px',
    border: '1px solid #E8E8EF',
    borderHover: '1px solid #644CF0',
    borderFocus: '1px solid #644CF0',
  },
  Select: {
    borderRadius: '12px',
    fontSizeMedium: '16px',
    fontSizeLarge: '16px',
    heightMedium: '44px',
    heightLarge: '48px',
  },
  Dialog: {
    borderRadius: '18px',
    titleFontSize: '20px',
    fontSize: '16px',
  },
  Modal: {
    borderRadius: '18px',
  },
  Message: {
    borderRadius: '12px',
    fontSize: '16px',
  },
  Menu: {
    borderRadius: '8px',
    itemTextColor: '#5a5a68',
    itemTextColorActive: '#644CF0',
    fontSize: '16px',
  },
  Progress: {
    railColor: '#F4F5F9',
    fillColor: '#644CF0',
  },
  Statistic: {
    valueFontSize: '32px',
    labelFontSize: '14px',
  },
  Tabs: {
    tabBorderRadius: '8px',
    tabFontSizeMedium: '16px',
    tabFontSizeLarge: '18px',
    tabFontSizeSmall: '14px',
    colorSegment: '#F4F5F9',
  },
  Pagination: {
    itemFontSize: '14px',
    buttonFontSize: '14px',
  },
  Form: {
    labelFontSizeTopMedium: '14px',
    feedbackFontSizeMedium: '14px',
  },
  Empty: {
    textColor: '#A0A0A8',
    fontSize: '14px',
  },
  Dropdown: {
    fontSize: '16px',
    optionTextColor: '#5a5a68',
    borderRadius: '12px',
  },
  Alert: {
    borderRadius: '12px',
  },
}
